# to find some executables TODO might not be needed
export PATH=$HOME/install/bin/:$PATH
export PATH=$HOME/pet_install/:$PATH
export PATH=$HOME/pluto_install/:$PATH
export PATH=$HOME/ClanPlugin/:$PATH

# to find the libraries 
export LD_LIBRARY_PATH=$HOME/install/lib/:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=$HOME/ClanPlugin/lib/:$LD_LIBRARY_PATH

export CPATH=$HOME/pluto_install/include/pluto/:$HOME/pluto_install/include/pluto_codegen_cxx:$HOME/pet_install/include/:$CPATH

alias vi='vim'
alias ls='ls -lh --color=auto'

export TERM=xterm
export EDITOR=vim

git config --global user.email "kemnitz.stefan@googlemail.com"
git config --global user.name "Stefan Kemnitz"

