#!/bin/bash
useradd -G users -o -u $uid $user
rm -r /usr/lib/libclang.so*
cp /root/install/lib/libclang.so* /usr/lib/ 
ln -s /usr/lib/libclang.so /usr/lib/libclang.so.4
ln -s /usr/lib/libclang.so /usr/lib/libclang.so.4.0
chown $user:users -R /root
cp -r /data/qtexample /home/$user/
mkdir -p /home/$user/.config/QtProject/
cp -r /data/QtCreator.ini /home/$user/.config/QtProject/QtCreator.ini
cp -r /data/config /home/$user/.config
cp -r /data/bashrc /home/$user/.bashrc
chown $user:users -R /home/$user/

# normal turboscript stuff
echo "$user ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
mkdir -p /home/$user/.vnc; printf "$pw" |/opt/TurboVNC/bin/vncpasswd -f > /home/$user/.vnc/passwd
chmod 600 /home/$user/.vnc/passwd
chown -R $user /home/$user/.vnc
cp /data/.xinitrc /home/$user/
chown $user /home/$user/.xinitrc
chown $user /home/$user
runuser -l $user -c "/opt/TurboVNC/bin/vncserver -fg -autokill"
